/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_securics_wildlifecapture_PerspectiveTransformationEngine */

#ifndef _Included_com_securics_wildlifecapture_PerspectiveTransformationEngine
#define _Included_com_securics_wildlifecapture_PerspectiveTransformationEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_securics_wildlifecapture_PerspectiveTransformationEngine
 * Method:    performTransform
 * Signature: (DDDLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_securics_wildlifecapture_PerspectiveTransformationEngine_performTransform
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jstring, jstring);

/*
 * Class:     com_securics_wildlifecapture_PerspectiveTransformationEngine
 * Method:    setCalibrationType
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_securics_wildlifecapture_PerspectiveTransformationEngine_setCalibrationType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_securics_wildlifecapture_PerspectiveTransformationEngine
 * Method:    runCalibration
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_securics_wildlifecapture_PerspectiveTransformationEngine_runCalibration
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_securics_wildlifecapture_PerspectiveTransformationEngine
 * Method:    setMinArea
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_securics_wildlifecapture_PerspectiveTransformationEngine_setMinArea
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_securics_wildlifecapture_PerspectiveTransformationEngine
 * Method:    setMaxArea
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_securics_wildlifecapture_PerspectiveTransformationEngine_setMaxArea
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_securics_wildlifecapture_PerspectiveTransformationEngine
 * Method:    setCamPitch
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_securics_wildlifecapture_PerspectiveTransformationEngine_setCamPitch
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_securics_wildlifecapture_PerspectiveTransformationEngine
 * Method:    setCamHeight
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_securics_wildlifecapture_PerspectiveTransformationEngine_setCamHeight
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_securics_wildlifecapture_PerspectiveTransformationEngine
 * Method:    doRevisedJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;DDDD)I
 */
JNIEXPORT jint JNICALL Java_com_securics_wildlifecapture_PerspectiveTransformationEngine_doRevisedJNI
  (JNIEnv *, jobject, jstring, jstring, jstring, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
