/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_securics_wildlifecapture_MainActivity */

#ifndef _Included_com_securics_wildlifecapture_MainActivity
#define _Included_com_securics_wildlifecapture_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_securics_wildlifecapture_MainActivity_CAM_3D
#define com_securics_wildlifecapture_MainActivity_CAM_3D 0L
/*
 * Class:     com_securics_wildlifecapture_MainActivity
 * Method:    doRevisedJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;DDDD)I
 */
JNIEXPORT jint JNICALL Java_com_securics_wildlifecapture_MainActivity_doRevisedJNI
  (JNIEnv *, jobject, jstring, jstring, jstring, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_securics_wildlifecapture_MainActivity
 * Method:    giveConfig
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_securics_wildlifecapture_MainActivity_giveConfig
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
