/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_vast_wildlifecam_MainActivity */

#ifndef _Included_edu_vast_wildlifecam_MainActivity
#define _Included_edu_vast_wildlifecam_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_vast_wildlifecam_MainActivity_CAM_3D
#define edu_vast_wildlifecam_MainActivity_CAM_3D 0L

/*
 * Class:     edu_vast_wildlifecam_MainActivity
 * Method:    pushImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jint JNICALL Java_edu_vast_wildlifecam_MainActivity_pushImage
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     edu_vast_wildlifecam_MainActivity
 * Method:    giveConfig
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_vast_wildlifecam_MainActivity_giveConfig
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     edu_vast_wildlifecam_MainActivity
 * Method:    getStartTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_vast_wildlifecam_MainActivity_getStartTime
  (JNIEnv *, jclass);

/*
 * Class:     edu_vast_wildlifecam_MainActivity
 * Method:    getEndTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_vast_wildlifecam_MainActivity_getEndTime
  (JNIEnv *, jclass);

/*
 * Class:     edu_vast_wildlifecam_MainActivity
 * Method:    getLogFile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_vast_wildlifecam_MainActivity_getLogFile
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
