/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libMR_boult_LibMR_TestActivity */

#ifndef _Included_libMR_boult_LibMR_TestActivity
#define _Included_libMR_boult_LibMR_TestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libMR_boult_LibMR_TestActivity
 * Method:    Weibull
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_libMR_boult_LibMR_1TestActivity_Weibull
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
