WildlifeCapture: com.securics.wildlifecapture.GeneralSettings Class Reference
com.securics.wildlifecapture.GeneralSettings Class Reference
Public Member Functions
GeneralSettings (Context context, AttributeSet attrs)
Protected Member Functions
void onBindView (View view)
Private Member Functions
void loadParams ()
Detailed Description
Definition at line 9 of file GeneralSettings.java.
Constructor & Destructor Documentation
com.securics.wildlifecapture.GeneralSettings.GeneralSettings (Context context, AttributeSet attrs)
Depending on tittle from context, input the array from either generalstuff or general_swindow
Parameters
context
attrs
Definition at line 22 of file GeneralSettings.java.
References com.securics.wildlifecapture.MainActivity.debugMode.
Member Function Documentation
void com.securics.wildlifecapture.GeneralSettings.loadParams () private
uses MyNumberPreference to load values to mp
Definition at line 54 of file GeneralSettings.java.
References com.securics.wildlifecapture.MyNumberPreference.setType().
Referenced by com.securics.wildlifecapture.GeneralSettings.onBindView().
void com.securics.wildlifecapture.GeneralSettings.onBindView (View view) protected
calls loadParams
Definition at line 44 of file GeneralSettings.java.
References com.securics.wildlifecapture.GeneralSettings.loadParams().
The documentation for this class was generated from the following file:
src/com/securics/wildlifecapture/GeneralSettings.java