WildlifeCapture: com.securics.wildlifecapture.TimePreference Class Reference
com.securics.wildlifecapture.TimePreference Class Reference
Classes
class SavedState
Public Member Functions
TimePreference (Context ctxt)
TimePreference (Context ctxt, AttributeSet attrs)
TimePreference (Context ctxt, AttributeSet attrs, int defStyle)
CharSequence getSummary ()
Protected Member Functions
View onCreateDialogView ()
void onBindDialogView (View v)
void onDialogClosed (boolean positiveResult)
Object onGetDefaultValue (TypedArray a, int index)
void onSetInitialValue (boolean restoreValue, Object defaultValue)
Parcelable onSaveInstanceState ()
void onRestoreInstanceState (Parcelable state)
Private Attributes
Calendar calendar
TimePicker picker = null
int theHour
String hour = "theHour" + getKey()
String minute = "theMinute" + getKey()
Detailed Description
Definition at line 23 of file TimePreference.java.
Constructor & Destructor Documentation
com.securics.wildlifecapture.TimePreference.TimePreference (Context ctxt)
sets context
Parameters
ctxt
Definition at line 34 of file TimePreference.java.
com.securics.wildlifecapture.TimePreference.TimePreference (Context ctxt, AttributeSet attrs)
set context and attribute
Parameters
ctxt
attrs
Definition at line 43 of file TimePreference.java.
com.securics.wildlifecapture.TimePreference.TimePreference (Context ctxt, AttributeSet attrs, int defStyle)
set context, attrs, and defstype. Set positive and negative button and set calendar as a new instance of GregorianCalendar
Parameters
ctxt
attrs
defStyle
Definition at line 54 of file TimePreference.java.
References com.securics.wildlifecapture.TimePreference.calendar.
Member Function Documentation
CharSequence com.securics.wildlifecapture.TimePreference.getSummary ()
gets value for theHour and theMinute, set calendar to the values and return date format of calendar
Definition at line 226 of file TimePreference.java.
References com.securics.wildlifecapture.TimePreference.calendar, com.securics.wildlifecapture.TimePreference.hour, com.securics.wildlifecapture.TimePreference.minute, and com.securics.wildlifecapture.TimePreference.theHour.
Referenced by com.securics.wildlifecapture.TimePreference.onDialogClosed(), and com.securics.wildlifecapture.TimePreference.onSetInitialValue().
void com.securics.wildlifecapture.TimePreference.onBindDialogView (View v) protected
set value for picker
Definition at line 76 of file TimePreference.java.
References com.securics.wildlifecapture.TimePreference.hour, com.securics.wildlifecapture.TimePreference.minute, and com.securics.wildlifecapture.TimePreference.theHour.
View com.securics.wildlifecapture.TimePreference.onCreateDialogView () protected
sets picker to the preference for TimePicker and return it
Definition at line 66 of file TimePreference.java.
References com.securics.wildlifecapture.TimePreference.picker.
void com.securics.wildlifecapture.TimePreference.onDialogClosed (boolean positiveResult) protected
get value for theHour and theMinute and save it to the editor
Definition at line 99 of file TimePreference.java.
References com.securics.wildlifecapture.TimePreference.calendar, com.securics.wildlifecapture.TimePreference.getSummary(), com.securics.wildlifecapture.TimePreference.hour, com.securics.wildlifecapture.TimePreference.minute, and com.securics.wildlifecapture.TimePreference.theHour.
Object com.securics.wildlifecapture.TimePreference.onGetDefaultValue (TypedArray a, int index) protected
returns the value of TypedArray a in the index if there is no value return 4
Definition at line 176 of file TimePreference.java.
void com.securics.wildlifecapture.TimePreference.onRestoreInstanceState (Parcelable state) protected
Set superState from the parameter to the subclass
Check whether we saved the state in onSaveInstanceState
Didn't save the state, so call superclass
Cast state to custom BaseSavedState and pass to superclass
Set this Preference's widget to reflect the restored state
Definition at line 284 of file TimePreference.java.
References com.securics.wildlifecapture.TimePreference.theHour.
Parcelable com.securics.wildlifecapture.TimePreference.onSaveInstanceState () protected
Create instance of custom BaseSavedState
Set the state's value with the class member that holds current
Definition at line 252 of file TimePreference.java.
References com.securics.wildlifecapture.TimePreference.hour, com.securics.wildlifecapture.TimePreference.minute, and com.securics.wildlifecapture.TimePreference.theHour.
void com.securics.wildlifecapture.TimePreference.onSetInitialValue (boolean restoreValue, Object defaultValue) protected
Sets calendar to proper values and save those values to editor
Definition at line 185 of file TimePreference.java.
References com.securics.wildlifecapture.MainActivity.debugMode, com.securics.wildlifecapture.TimePreference.getSummary(), com.securics.wildlifecapture.TimePreference.hour, com.securics.wildlifecapture.TimePreference.minute, and com.securics.wildlifecapture.TimePreference.theHour.
Member Data Documentation
Calendar com.securics.wildlifecapture.TimePreference.calendar private
Definition at line 24 of file TimePreference.java.
Referenced by com.securics.wildlifecapture.TimePreference.getSummary(), com.securics.wildlifecapture.TimePreference.onDialogClosed(), and com.securics.wildlifecapture.TimePreference.TimePreference().
String com.securics.wildlifecapture.TimePreference.hour = "theHour" + getKey() private
Definition at line 27 of file TimePreference.java.
Referenced by com.securics.wildlifecapture.TimePreference.getSummary(), com.securics.wildlifecapture.TimePreference.onBindDialogView(), com.securics.wildlifecapture.TimePreference.onDialogClosed(), com.securics.wildlifecapture.TimePreference.onSaveInstanceState(), and com.securics.wildlifecapture.TimePreference.onSetInitialValue().
String com.securics.wildlifecapture.TimePreference.minute = "theMinute" + getKey() private
Definition at line 28 of file TimePreference.java.
Referenced by com.securics.wildlifecapture.TimePreference.getSummary(), com.securics.wildlifecapture.TimePreference.onBindDialogView(), com.securics.wildlifecapture.TimePreference.onDialogClosed(), com.securics.wildlifecapture.TimePreference.onSaveInstanceState(), and com.securics.wildlifecapture.TimePreference.onSetInitialValue().
TimePicker com.securics.wildlifecapture.TimePreference.picker = null private
Definition at line 25 of file TimePreference.java.
Referenced by com.securics.wildlifecapture.TimePreference.onCreateDialogView().
int com.securics.wildlifecapture.TimePreference.theHour private
Definition at line 26 of file TimePreference.java.
Referenced by com.securics.wildlifecapture.TimePreference.getSummary(), com.securics.wildlifecapture.TimePreference.onBindDialogView(), com.securics.wildlifecapture.TimePreference.onDialogClosed(), com.securics.wildlifecapture.TimePreference.onRestoreInstanceState(), com.securics.wildlifecapture.TimePreference.onSaveInstanceState(), and com.securics.wildlifecapture.TimePreference.onSetInitialValue().
The documentation for this class was generated from the following file:
src/com/securics/wildlifecapture/TimePreference.java