WildlifeCapture: com.securics.wildlifecapture.ActivityDebug Class Reference
com.securics.wildlifecapture.ActivityDebug Class Reference
Public Member Functions
ActivityDebug (String lf)
void EndPhotoSnapperDebug ()
void logHeap (Class<?> clazz)
void setID (String ID)
void logMessage (String tag, String message)
Public Attributes
BroadcastReceiver batteryInfoReceiver
Private Member Functions
float[] readUsage ()
Private Attributes
final long DELAY = 1000 * 30
String myID = "notset"
Handler PSHandler = new Handler()
final String LOG_FILE
Thread ReadingUsage
Static Private Attributes
static final String TAG = "MyDebug"
Detailed Description
Definition at line 22 of file ActivityDebug.java.
Constructor & Destructor Documentation
com.securics.wildlifecapture.ActivityDebug.ActivityDebug (String lf)
Set LOG_FILE name and add ReadingUsage to message Queue
Parameters
lf
Definition at line 40 of file ActivityDebug.java.
References com.securics.wildlifecapture.ActivityDebug.LOG_FILE, and com.securics.wildlifecapture.ActivityDebug.ReadingUsage.
Member Function Documentation
void com.securics.wildlifecapture.ActivityDebug.EndPhotoSnapperDebug ()
Removes pending post from ReadingUsage
Definition at line 48 of file ActivityDebug.java.
References com.securics.wildlifecapture.ActivityDebug.ReadingUsage.
void com.securics.wildlifecapture.ActivityDebug.logHeap (Class<?> clazz)
display head usage
Parameters
clazz
Definition at line 143 of file ActivityDebug.java.
References com.securics.wildlifecapture.ActivityDebug.logMessage(), and com.securics.wildlifecapture.ActivityDebug.TAG.
void com.securics.wildlifecapture.ActivityDebug.logMessage (String tag, String message)
writes message in text file LOG_FILE
Parameters
tag
message
Definition at line 173 of file ActivityDebug.java.
References com.securics.wildlifecapture.MainActivity.debugMode, com.securics.wildlifecapture.ActivityDebug.LOG_FILE, and com.securics.wildlifecapture.ActivityDebug.myID.
Referenced by com.securics.wildlifecapture.ActivityDebug.logHeap(), and com.securics.wildlifecapture.ActivityDebug.readUsage().
float [] com.securics.wildlifecapture.ActivityDebug.readUsage () private
reads CPU usage
Definition at line 56 of file ActivityDebug.java.
References com.securics.wildlifecapture.MainActivity.debugMode, com.securics.wildlifecapture.ActivityDebug.logMessage(), and com.securics.wildlifecapture.ActivityDebug.TAG.
void com.securics.wildlifecapture.ActivityDebug.setID (String ID)
gets ID
Parameters
ID
Definition at line 164 of file ActivityDebug.java.
References com.securics.wildlifecapture.ActivityDebug.myID.
Member Data Documentation
BroadcastReceiver com.securics.wildlifecapture.ActivityDebug.batteryInfoReceiver
gets level, scale, status, and teperature of battery
Definition at line 203 of file ActivityDebug.java.
final long com.securics.wildlifecapture.ActivityDebug.DELAY = 1000 * 30 private
Definition at line 27 of file ActivityDebug.java.
final String com.securics.wildlifecapture.ActivityDebug.LOG_FILE private
Definition at line 34 of file ActivityDebug.java.
Referenced by com.securics.wildlifecapture.ActivityDebug.ActivityDebug(), and com.securics.wildlifecapture.ActivityDebug.logMessage().
String com.securics.wildlifecapture.ActivityDebug.myID = "notset" private
Definition at line 29 of file ActivityDebug.java.
Referenced by com.securics.wildlifecapture.ActivityDebug.logMessage(), and com.securics.wildlifecapture.ActivityDebug.setID().
Handler com.securics.wildlifecapture.ActivityDebug.PSHandler = new Handler() private
Definition at line 31 of file ActivityDebug.java.
Thread com.securics.wildlifecapture.ActivityDebug.ReadingUsage private
Initial value:
= new Thread() {
        @Override
        public void run() {
            readUsage();
            PSHandler.postDelayed(ReadingUsage, DELAY);
        }
    }
runs ReadUsage ina different thread and post it to the message queue
Definition at line 253 of file ActivityDebug.java.
Referenced by com.securics.wildlifecapture.ActivityDebug.ActivityDebug(), and com.securics.wildlifecapture.ActivityDebug.EndPhotoSnapperDebug().
final String com.securics.wildlifecapture.ActivityDebug.TAG = "MyDebug" static private
Definition at line 24 of file ActivityDebug.java.
Referenced by com.securics.wildlifecapture.ActivityDebug.logHeap(), and com.securics.wildlifecapture.ActivityDebug.readUsage().
The documentation for this class was generated from the following file:
src/com/securics/wildlifecapture/ActivityDebug.java