WildlifeCapture: com.securics.wildlifecapture.ResetDefaults.MyFAQ Class Reference
com.securics.wildlifecapture.ResetDefaults.MyFAQ Class Reference
Public Member Functions
MyFAQ ()
MyFAQ (Context context, AttributeSet attrs, int defStyle)
MyFAQ (Context context, AttributeSet attrs)
void setText (String text)
String getText ()
void onClick (DialogInterface dialog, int which)
Protected Member Functions
View onCreateDialogView ()
void onBindDialogView (View view)
Private Member Functions
boolean resetAllSettings ()
Private Attributes
TextView mEditText
String mText
Detailed Description
Definition at line 44 of file ResetDefaults.java.
Constructor & Destructor Documentation
com.securics.wildlifecapture.ResetDefaults.MyFAQ.MyFAQ ()
Initialize question and answer. Set dialog title and title to variable question, set summary to Reset All Settings, and text to variable answer
Definition at line 52 of file ResetDefaults.java.
References com.securics.wildlifecapture.ResetDefaults.MyFAQ.setText().
com.securics.wildlifecapture.ResetDefaults.MyFAQ.MyFAQ (Context context, AttributeSet attrs, int defStyle)
Uses function super to call parent constructor with parameters context, attrs, and defStyle
Parameters
context
attrs
defStyle
Definition at line 70 of file ResetDefaults.java.
com.securics.wildlifecapture.ResetDefaults.MyFAQ.MyFAQ (Context context, AttributeSet attrs)
Uses function super to call parent constructor with parameters context and attrs
Parameters
context
attrs
Definition at line 79 of file ResetDefaults.java.
Member Function Documentation
String com.securics.wildlifecapture.ResetDefaults.MyFAQ.getText ()
Returns mText
Returns
Definition at line 105 of file ResetDefaults.java.
References com.securics.wildlifecapture.ResetDefaults.MyFAQ.mText.
void com.securics.wildlifecapture.ResetDefaults.MyFAQ.onBindDialogView (View view) protected
Set mText as text for mEditText
Definition at line 113 of file ResetDefaults.java.
References com.securics.wildlifecapture.ResetDefaults.MyFAQ.mText.
void com.securics.wildlifecapture.ResetDefaults.MyFAQ.onClick (DialogInterface dialog, int which)
Manage feedback from buttons
Definition at line 121 of file ResetDefaults.java.
References com.securics.wildlifecapture.ResetDefaults.MyFAQ.mText, and com.securics.wildlifecapture.ResetDefaults.MyFAQ.resetAllSettings().
View com.securics.wildlifecapture.ResetDefaults.MyFAQ.onCreateDialogView () protected
Definition at line 86 of file ResetDefaults.java.
References com.securics.wildlifecapture.ResetDefaults.MyFAQ.mEditText.
boolean com.securics.wildlifecapture.ResetDefaults.MyFAQ.resetAllSettings () private
Resets squirrel and window params, camera, schedule, capture Schedule settings and file and folder locations to default.
Returns
General Squirrel Params
Sliding Window Params
Camera Settings
Capture Schedule Settings
File and Folder locations
Definition at line 142 of file ResetDefaults.java.
Referenced by com.securics.wildlifecapture.ResetDefaults.MyFAQ.onClick().
void com.securics.wildlifecapture.ResetDefaults.MyFAQ.setText (String text)
Set mText to text
Parameters
text
Definition at line 97 of file ResetDefaults.java.
References com.securics.wildlifecapture.ResetDefaults.MyFAQ.mText.
Referenced by com.securics.wildlifecapture.ResetDefaults.MyFAQ.MyFAQ().
Member Data Documentation
TextView com.securics.wildlifecapture.ResetDefaults.MyFAQ.mEditText private
Definition at line 83 of file ResetDefaults.java.
Referenced by com.securics.wildlifecapture.ResetDefaults.MyFAQ.onCreateDialogView().
String com.securics.wildlifecapture.ResetDefaults.MyFAQ.mText private
Definition at line 92 of file ResetDefaults.java.
Referenced by com.securics.wildlifecapture.ResetDefaults.MyFAQ.getText(), com.securics.wildlifecapture.ResetDefaults.MyFAQ.onBindDialogView(), com.securics.wildlifecapture.ResetDefaults.MyFAQ.onClick(), and com.securics.wildlifecapture.ResetDefaults.MyFAQ.setText().
The documentation for this class was generated from the following file:
src/com/securics/wildlifecapture/ResetDefaults.java