WildlifeCapture: com.securics.wildlifecapture.ChangeResolutionActivity Class Reference
com.securics.wildlifecapture.ChangeResolutionActivity Class Reference
Public Member Functions
void getSizeData ()
void sizeToString ()
void setListView ()
boolean onCreateOptionsMenu (Menu menu)
void onListItemClick (ListView tmp, View v, int pos, long id)
Protected Member Functions
void onCreate (Bundle savedInstanceState)
void onResume ()
Private Member Functions
Camera getCameraInstance ()
Private Attributes
ListView internalView
Camera camCopy
Size picSize
List< Size > sizeList
String[] sizeNames
Detailed Description
Definition at line 16 of file ChangeResolutionActivity.java.
Member Function Documentation
Camera com.securics.wildlifecapture.ChangeResolutionActivity.getCameraInstance () private
Attempt to get a camera.
Definition at line 135 of file ChangeResolutionActivity.java.
References com.securics.wildlifecapture.MainActivity.debugMode.
Referenced by com.securics.wildlifecapture.ChangeResolutionActivity.onResume().
void com.securics.wildlifecapture.ChangeResolutionActivity.getSizeData ()
This should probably be able to potentially maybe get the sizeList from the non-static copy of the static camera contained in MainActivity.
Definition at line 28 of file ChangeResolutionActivity.java.
References com.securics.wildlifecapture.ChangeResolutionActivity.sizeList.
Referenced by com.securics.wildlifecapture.ChangeResolutionActivity.onResume().
void com.securics.wildlifecapture.ChangeResolutionActivity.onCreate (Bundle savedInstanceState) protected
set layout
Definition at line 75 of file ChangeResolutionActivity.java.
boolean com.securics.wildlifecapture.ChangeResolutionActivity.onCreateOptionsMenu (Menu menu)
Create an option menu
Inflate the menu; this adds items to the action bar if it is present.
Definition at line 109 of file ChangeResolutionActivity.java.
void com.securics.wildlifecapture.ChangeResolutionActivity.onListItemClick (ListView tmp, View v, int pos, long id)
Set resolution on MainActivity
Definition at line 118 of file ChangeResolutionActivity.java.
References com.securics.wildlifecapture.ChangeResolutionActivity.camCopy, and com.securics.wildlifecapture.ChangeResolutionActivity.sizeNames.
void com.securics.wildlifecapture.ChangeResolutionActivity.onResume () protected
get instance of camera
Definition at line 85 of file ChangeResolutionActivity.java.
References com.securics.wildlifecapture.ChangeResolutionActivity.camCopy, com.securics.wildlifecapture.ChangeResolutionActivity.getCameraInstance(), com.securics.wildlifecapture.ChangeResolutionActivity.getSizeData(), com.securics.wildlifecapture.ChangeResolutionActivity.internalView, com.securics.wildlifecapture.ChangeResolutionActivity.setListView(), and com.securics.wildlifecapture.ChangeResolutionActivity.sizeToString().
void com.securics.wildlifecapture.ChangeResolutionActivity.setListView ()
set list adapter
Set up the array adapter.
Definition at line 64 of file ChangeResolutionActivity.java.
References com.securics.wildlifecapture.ChangeResolutionActivity.sizeNames.
Referenced by com.securics.wildlifecapture.ChangeResolutionActivity.onResume().
void com.securics.wildlifecapture.ChangeResolutionActivity.sizeToString ()
Add all picture sizes to sizeNames array
Definition at line 39 of file ChangeResolutionActivity.java.
References com.securics.wildlifecapture.ChangeResolutionActivity.sizeList, and com.securics.wildlifecapture.ChangeResolutionActivity.sizeNames.
Referenced by com.securics.wildlifecapture.ChangeResolutionActivity.onResume().
Member Data Documentation
Camera com.securics.wildlifecapture.ChangeResolutionActivity.camCopy private
Definition at line 19 of file ChangeResolutionActivity.java.
Referenced by com.securics.wildlifecapture.ChangeResolutionActivity.onListItemClick(), and com.securics.wildlifecapture.ChangeResolutionActivity.onResume().
ListView com.securics.wildlifecapture.ChangeResolutionActivity.internalView private
Definition at line 18 of file ChangeResolutionActivity.java.
Referenced by com.securics.wildlifecapture.ChangeResolutionActivity.onResume().
Size com.securics.wildlifecapture.ChangeResolutionActivity.picSize private
Definition at line 20 of file ChangeResolutionActivity.java.
List<Size> com.securics.wildlifecapture.ChangeResolutionActivity.sizeList private
Definition at line 21 of file ChangeResolutionActivity.java.
Referenced by com.securics.wildlifecapture.ChangeResolutionActivity.getSizeData(), and com.securics.wildlifecapture.ChangeResolutionActivity.sizeToString().
String [] com.securics.wildlifecapture.ChangeResolutionActivity.sizeNames private
Definition at line 22 of file ChangeResolutionActivity.java.
Referenced by com.securics.wildlifecapture.ChangeResolutionActivity.onListItemClick(), com.securics.wildlifecapture.ChangeResolutionActivity.setListView(), and com.securics.wildlifecapture.ChangeResolutionActivity.sizeToString().
The documentation for this class was generated from the following file:
src/com/securics/wildlifecapture/ChangeResolutionActivity.java